### PR TITLE
Group transfer popup

### LINKED ISSUE #163: Group preview
Remove or transfer

- transfer dialog can be opened via button in bottom
- Edit subgroups on group popup
- Archive should be with confirmation

### PR DESCRIPTION
**Pull request by tsumo**
## PR includes

-   [x] Feature

### CODE REVIEW

**Review by nyet-ty — APPROVED** [review]

**Comment by tsumo** [comment]
#163

**Comment by tsumo** [comment]
Looks ugly, but it works
Screenshot 2023-09-26 at 10 37 49

**Comment by 9teen90nine** [comment]
Should use regular form with bottom buttons and an autocomplete from bricks

**Comment by tsumo** [comment]
Cool new form 😎 

Screenshot 2023-09-26 at 20 04 49
Screenshot 2023-09-26 at 20 05 00

**Review by 9teen90nine — APPROVED** [review]

**Pull request merged**
